# runhw1.py -- runs every Part F question in order. No mathematics in this file.
import hw1

print("Output of question 1 part a : ", hw1.q1a())
print("Output of question 1 part b : ", hw1.q1b())
print("Output of question 1 part c : ", hw1.q1c())
print("Output of question 1 part d : ", hw1.q1d())
print("Output of question 1 part e : ", hw1.q1e())
print("Output of question 1 part f : ", hw1.q1f())
print("Output of question 1 part g : ", hw1.q1g())
print("Output of question 1 part h : ", hw1.q1h())
print("Output of question 1 part i : ", hw1.q1i())
print("Output of question 2 part a : ", hw1.q2a())
print("Output of question 2 part b : ", hw1.q2b())
print("Output of question 2 part c : ", hw1.q2c())
print("Output of question 3 : ", hw1.q3())
print("Output of question 4 part a : ", hw1.q4a())
print("Output of question 4 part b : ", hw1.q4b())
print("Output of question 4 part c : ", hw1.q4c())
print("Output of question 4 part d : ", hw1.q4d())
print("Output of question 5 part a : ", hw1.q5a())
print("Output of question 5 part b : ", hw1.q5b())
print("Output of question 5 part c : ", hw1.q5c())
print("Output of question 6 part a : ", hw1.q6a())
print("Output of question 6 part b : ", hw1.q6b())
print("Output of question 6 part c : ", hw1.q6c())
print("Output of question 6 part d : ", hw1.q6d())
print("Output of question 7 part a : ", hw1.q7a())
print("Output of question 7 part b : ", hw1.q7b())
print("Output of question 7 part c : ", hw1.q7c())
print("Output of question 7 part d : ", hw1.q7d())
print("Output of question 8 : ", hw1.q8())
